### ISSUE TITLE
Add a DOI for hop-client

### ISSUE THREAD

**Issue by bfc5288** [scimma/hop-client#71]
### Description
As a user, I would like to be able to cite a `hop client` release in a program or publication.

This can be done with Github integrations, such as [Zenodo](https://guides.github.com/activities/citable-code/).

### Definition of Done
Each release of `hop-client` has an associated DOI.

### Tasks/Items:
- [x] Assess options for DOI-citable software
- [x] Add integrations/webhooks/etc. to the repo/project as required by the DOI service
- [x] Check that [releases](https://github.com/scimma/hop-client/releases) have DOIs

**Comment by bfc5288** [comment]
Zenodo integration has been added. A DOI should be generated by the next release (previous releases can't be added in this way, according to their [docs](https://help.zenodo.org/)).
