### ISSUE TITLE
Implement UNIX-like piping to publish messages 

### ISSUE THREAD

**Issue by bfc5288** [scimma/hop-client#86]
### Description

As a user, I would like to pipe raw strings directly from the CLI or from a file into `hop publish` in a UNIX-like fashion, e.g.:
```
"This is my message" | hop publish kafka://host:port/topic
```
or
```
cat stringlist.txt | hop publish kafka://host:port/topic
```

See [discussion](https://github.com/scimma/hop-client/pull/82#discussion_r449690982) in #82. 

### Definition of Done
A command like `cat stringlist.txt | hop publish kafka://host:port/topic` publishes the strings from `stringlist.txt` as message(s), while also respecting the formatting of the strings (if any) and mapping this to the corresponding message datamodel.

### Tasks/Items:
- [x] Change CLI argument settings as needed
- [ ] Verify for each format datamodel
- [ ] Write unit tests
